### ISSUE TITLE
play-slick導入

### ISSUE THREAD

**Issue by keicy** [keicy/whisky-taste#9]
#8 の作業途中にて実施した。ログとしてこちらに切り出しておく。

[play-slick](https://github.com/playframework/play-slick)

- ORマッパ,DBアクセスツール
- https://github.com/playframework/play-slick#all-releases
  - 使用する play のバージョンによって対応するバージョンが違うので導入時に注意

**Comment by keicy** [comment]
play のバージョンによってライブラリの対応バージョンも違うので要注意！

ここでは Play2.5.10 を想定する
※ Play のバージョン確認は `project/plugins.sbt` を参照

https://www.playframework.com/documentation/2.5.x/PlaySlick

※ 2.6はこちら参照
※ https://www.playframework.com/documentation/2.6.x/PlaySlick

使うバージョン対応表
https://github.com/playframework/play-slick#all-releases
→今回は play-slick 2.1.0 が最新版とのこと


# build.sbtにslick向けの設定を追加

最新の2.1.0を使うことにするので下記を追記する


libraryDependencies ++= Seq(
~
  "com.typesafe.play" %% "play-slick" % "2.1.0",
  "com.typesafe.play" %% "play-slick-evolutions" % "2.1.0",
  "com.h2database" % "h2" % "1.4.196"
)

※ `evolutions` パッケージは、 `play-slick-evolutions` に含まれるので不要
※ もし過去に追記しているようならこのタイミングで削除する

※ また、公式ドキュメントには書いていないが、検索すると `jdbc` パッケージも
※ play-slickと競合するため削除する”必要がある”と書いてあった。
※ 一度削除せずやってみて、だめなら消してみる。
↓
【追記】
結論、消す必要があった。消さないと下記エラーが発生しアプリが起動しない。

```
Unexpected exception
CreationException: Unable to create injector, see the following errors:

1) A binding to play.api.db.DBApi was already configured at play.api.db.DBModule.bindings(DBModule.scala:25):
Binding(interface play.api.db.DBApi to ProviderConstructionTarget(class play.api.db.DBApiProvider)) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1).
  at play.api.db.slick.evolutions.EvolutionsModule.bindings(EvolutionsModule.scala:15):
Binding(interface play.api.db.DBApi to ConstructionTarget(class play.api.db.slick.evolutions.internal.DBApiAdapter) in interface javax.inject.Singleton) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)

1 error
```

→公式FAQにその旨あった。
https://playframework.com/documentation/ja/2.4.x/PlaySlickFAQ#Changing-the-connection-pool-used-by-Slick


# application.conf に設定追加

結論、全体としてこうなった。

```
# こちらは jdbc を使ってDBアクセスする場合の設定
# play-slick を使う場合は不要（使用されない無意味な設定）
db {
  # You can declare as many datasources as you want.
  # By convention, the default datasource is named `default`

  # https://www.playframework.com/documentation/latest/ScalaDatabase
  # https://www.playframework.com/documentation/latest/Developing-with-the-H2-Database
  # default.driver = org.h2.Driver
  # default.url = "jdbc:h2:mem:play;MODE=MYSQL" # inmemory
  # default.url = "jdbc:h2:./h2db;MODE=MYSQL" # file
  # default.username = sa
  # default.password = ""

  # You can turn on SQL logging for any datasource
  # https://www.playframework.com/documentation/latest/Highlights25#Logging-SQL-statements
  #default.logSql=true
}

# こちらは play-slick を使ってDBアクセスする場合の設定
# https://www.playframework.com/documentation/latest/PlaySlick
slick.dbs {
  # Default database configuration
  default.driver="slick.driver.H2Driver$"
  default.db.driver="org.h2.Driver"
  #default.db.url="jdbc:h2:mem:play;MODE=MYSQL;DB_CLOSE_DELAY=-1"
  default.db.url="jdbc:h2:./h2db;MODE=MYSQL;DB_CLOSE_DELAY=-1"
  default.db.user=sa
  default.db.password=""
}
```

要点

- db.* 系の設定は全て、 jdbc を用いたDBアクセス、Evolutionの設定なので、play-slickを使う場合は不要。全て削除。
- slick.dbs.* 系の設定が play-slick を使う場合のDBアクセス、Evolutionの設定。こちらだけ有効にすれば良い。
- 必ず `DB_CLOSE_DELAY=-1` が必要。これがないと内部で無限ループが発生してEvolutionが発動しないとのこと。
  - https://www.playframework.com/documentation/2.6.x/Developing-with-the-H2-Database#prevent-in-memory-db-reset

# 結論

以上2設定を実施すれば導入完了。DBアクセスも Evolutionも正常動作するようになっている。
